---
title: "Week 3: Classical Approaches"
date: "2026-09-07"
format: 
  revealjs:
    css: /resources/custom_css.css
    theme: white
    progress: true
    transition: convex
    reveal_plugins: ['notes']
---

## Today's Dad Joke

Who is in favor or bringing back Roman numerals?

<span class="fragment">I for one!</span>

## Housekeeping

> - Reading review assignments
> - Group 4's presentation
> - Case study debrief
>   - What did you think about differently after the case study?


## Class Questions

> - What do you want to talk about today?

## Basic Concepts

> - What is the machine metaphor?
> - What are Fayol's principles of organizational structure, power, reward, and attitude?
> - Which aspects ring true and which aspects seem outdated?

## Basic Concepts (cont.)

> - What is Taylor's theory of scientific management?
> - What role does communication play in these classical approaches?
> - What role do classical approaches have in contemporary organizations?


## Reading Review Questions

 > - Does Taylor's management model prevent innovation in the workplace?
 > - Do you think that the classical approach could still be effective in modern-day workplaces, or do organizations need to focus on giving employees more flexibility than the classical approach does?
 > - What is the difference between traditional and charismatic authority versus rational-legal authority in bureaucratic functioning.

 ## Reading Review Questions (cont.)

 > - Who has the most influence over communication in an organization: managers, employees, or the organization structure itself?
 > - How do the three theories discussed in the textbook motivate lower-wage employees to work efficiently and diligently when employees are viewed primarily as components of the organizational machine?
 > - When is the line crossed that rules, and clear hierarchy become too much and actually make an organization less efficient?